name: First Github Actions Pipeline

on:
  push:
    branches:
      - master
    
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build On Master Push
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


